version: "3.9"

services:
  db:
    image: postgres:15
    container_name: vra_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: vra_django
    command: >
      sh -c "docker/wait-for-db.sh db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn vra_fms.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: