# Generated by Django 4.2.28 on 2026-02-21 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped – File Already Retrieved')], default='scheduled', max_length=20)),
                ('job_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='files.managedfile')),
            ],
            options={
                'verbose_name': 'File Reminder',
                'verbose_name_plural': 'File Reminders',
                'ordering': ['scheduled_for'],
            },
        ),
    ]
